### ISSUE TITLE
i get error when the action run 

### ISSUE THREAD

**Issue by ayadim** [projectdiscovery/naabu-action#2]
hi,
each time I run the naabu - workflow I get the same error: "Error: Process completed with exit code 2.".
any solution?

**Comment by ehsandeep** [comment]
@ayadim thanks for creating this issue, it should be now fixed with https://github.com/projectdiscovery/naabu-action/pull/3

**Comment by ayadim** [comment]
thank u for the response. i face a problem also with nuclei-action !

regards

**Comment by ayadim** [comment]
it was fixed thank u.
